### ISSUE TITLE
volunteers for new maintainer

### ISSUE THREAD

**Issue by michaelglass** [emilioforrer/haml_coffee_assets#130]
@thedeeno, @jimmycuadra, @jayzes, would any of y'all take the reigns on this repository now that we've sadly lost @netzpirat? (It appears he passed away in early April :cry:).

**Comment by manusajith** [comment]
following this thread to get updated of the changes.

**Comment by jimmycuadra** [comment]
@manusajith Just hit the "subscribe" button in the right sidebar. You don't have to comment to subscribe.

**Comment by huetsch** [comment]
Just upgraded my execjs and our code here choked due to the whitespace before the global flag which is referenced in both pull requests (for reference: https://github.com/netzpirat/haml_coffee_assets/pull/135). I noticed that those pull requests were indicating a failing build, but I glanced at them and didn't immediately see the issue. I'm wondering if perhaps the specs have fallen out of date? I'm not familiar with the details of the auto-build system.

I don't see a compelling reason why removing the extra whitespace would cause a problem, and it seems a silly reason to let the whole codebase become obsolete. Would anyone care to merge one of the pull requests? Also, can anyone comment on build situation?

**Comment by piston47** [comment]
@huetsch FYI Build seems to have failed due to some errror with the Jasmine server (see https://travis-ci.org/netzpirat/haml_coffee_assets/jobs/49267960#L215).  Possibly an environment issue as each subsequent build seems to have failed due to Jasmine server issues.

**Comment by cohei** [comment]
@thedeeno RubyGems staff seems to need your account's email. If you haven't noticed, please see [here](http://help.rubygems.org/discussions/problems/17925-abandoned-gem-nominee-for-new-maintainer).

**Comment by neerfri** [comment]
@thedeeno Thanks for taking this upon you.

Was there any progress on getting access from the rubygems guys?
We are currently waiting for this in order to update our app's dependencies. Should we wait or should we use one of the forks via git?

Thanks again!

**Comment by TheKidCoder** [comment]
Closing. @emilioforrer has taken the owner rains and I believe has access to rubygems as well.

**Comment by thedeeno** [comment]
@emilioforrer nice! Thanks for taking this over 👏
