### ISSUE TITLE
small deprecation warning, rails 5

### ISSUE THREAD

**Issue by masterkain** [emilioforrer/haml_coffee_assets#162]
DEPRECATION WARNING: Passing #original_exception is deprecated and has no effect. Exceptions will automatically capture the original exception. (called from new at /Users/kain/.rvm/gems/ruby-2.4.1/gems/haml_coffee_assets-1.17.0/lib/haml_coffee_assets/action_view/patches.rb:33)

**Comment by thoughtless** [comment]
While the deprecation warning is annoying, this is actually handled on Rails 5.1 by this PR, which is in 1.18.0. https://github.com/emilioforrer/haml_coffee_assets/pull/164

Since Rails 5.0 is not supported anymore (now that 5.2 has been released), I think that this issue should be closed. It might be possible to modify https://github.com/emilioforrer/haml_coffee_assets/blob/v1.18.0/lib/haml_coffee_assets/action_view/patches.rb#L32 to also work with Rails 5.0, but I don't think more effort should go into an unsupported version of Rails.
