### ISSUE TITLE
Jasmine failures with ruby 2.5

### ISSUE THREAD

**Issue by mathieujobin** [emilioforrer/haml_coffee_assets#178]
Could anyone explain why this Jasmine failures occurs with ruby 2.5 ?

https://travis-ci.org/github/emilioforrer/haml_coffee_assets/jobs/760066337

**Comment by mathieujobin** [comment]
![image](https://user-images.githubusercontent.com/99191/108784187-2b899f00-75b2-11eb-9060-4678ef04f77c.png)

**Comment by mathieujobin** [comment]
@TheKidCoder @tiagotex anyone of you know how to fix this?

**Comment by mathieujobin** [comment]
I don't know how, but #180 apparently fixed that as well

**Comment by derSascha** [comment]
@mathieujobin sprockets 4 seems to require always a file type suffix. befor the changes, jasmine loads `hamlcoffee_spec.coffee` and this returns the source coffeescript file instead of compiled javascript. loading `hamlcoffee_spec.js` in jasmine fixed the problem (https://github.com/emilioforrer/haml_coffee_assets/pull/180/commits/d1136a8e4d8a266829335078bad10ca1e91a3d37#diff-29034a88b600643d523a3eef2403e9058c03d280bcd0e458335f0f83913183cdR53).

**Comment by mathieujobin** [comment]
@derSascha I'm not quite understanding you? the fix is from you... is there a problem that remain? or you are just explaining your fix?
